### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by prtkdave** [kubean-io/kubean#993]
**usage issue**
1. doubts about how to use the software

I need to understand how do I increase the backoffLimit for the job  it creates to install kubernetes.
I basically want to attempt installation multiple times . Is it possible?

**Comment by prtkdave** [comment]
@ErikJiang  it would be great help , if you can guide me for above. thanks

**Comment by tu1h** [comment]
We removed `backoffLimit` since [v0.8.0](https://github.com/kubean-io/kubean/commit/59d57870897c5144d1a02eccdf270ae18985f36a).

These are reasons:
Almost failures during the job was caused by the sluggish network, and on the other hand a lot of retrying logic for that in Kubespray. If it is still failed, we consider that it is generally cannot resilient after job restarting, maybe there are some brokens in your operating system. Overall, Kubespray is not completely reentrant, so we removed `backoffLimit`.

But for workarroud, if you still want to use `backoffLimit`, you could downgrade kubean version to below `v0.8.0`

**Comment by prtkdave** [comment]
@tu1h  thanks for your response. I understand that you have removed backoffLimit for valid reasons that you have mentioned. I was wondering if it is possible to give an option to user(as an optional argument which can be defaulted to backoffLimit to 0) in helm chart deployment. I would be helpful for us. 

Thank you.

**Comment by ErikJiang** [comment]
Hi @prtkdave, we're actually interested in understanding your specific usage scenario, why is `backoffLimit` needed in your scenario?

I'd also like to add an explanation as to why we'd want to remove `backoffLimit`, one important reason is that operating a cluster is a relatively prudent behavior.

For example, when performing an upgrade operation, we'd rather create a new `ClusterOperation` after a failed one than have the job automatically retry, which creates a lot of uncertainty and destroys the scene of the crime, making it more expensive to troubleshoot.
